name: 'Stale Branches'
description: 'Clean up stale branches (branches that do not have any open merge requests)'
inputs:
  gh-token:  # id of input
    description: 'GitHub token to access GH CLI'
    required: true
outputs:
  branches-list:
    description: "List of branches to be cleaned up"
    value: ${{ steps.fetch-prs.outputs.branches }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Fetch open pull requests
      id: fetch-prs
      shell: bash
      run: fetch-prs.sh 
      continue-on-error: false
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
